float triangle_ray_distance(int triangle_index, Ray ray);
float sphere_ray_distance(int sphere_index, Ray ray);
void compute_local_coordinate_system(float4 normal, float4 *restrict t_1, float4 *restrict t_2);
float4 lambertian_on_hemisphere(float4 normal, float4 t_1, float4 t_2, unsigned long *restrict state);
float4 specular_on_hemisphere(float4 normal, float4 incoming_direction);
float compute_brdf(float4 incoming_direction, float4 outgoing_direction, float4 normal, float refractive_index_1, float refractive_index_2, float lambertian_probability, bool is_opaque);
float compute_brdf_lambertian(float4 outgoing_direction, float4 normal);
float4 random_on_triangle(unsigned int triangle_index, unsigned long *restrict state);
float4 random_on_sphere(unsigned int sphere_index, unsigned long *restrict state);
bool point_in_triangle(float4 point, float4 node_0, float4 node_1, float4 node_2);
bool same_side(float4 test_point, float4 point_inside, float4 first_node, float4 second_node);
unsigned int next_uint(unsigned long *restrict state);
unsigned int next_uint_in_range(unsigned int inclusive_minimum, unsigned int exclusive_maximum, unsigned long *restrict state);
float next_float(unsigned long *restrict state);
void pcg_init(unsigned long seed, unsigned long *restrict state);
Hitpoint compute_hitpoint(Ray ray, float4 accumulated_color);
float4 compute_direct_light(Ray ray, Hitpoint hitpoint, unsigned long *restrict state);
float4 compute_direct_light_inner(Hitpoint hitpoint, float4 light_color, float4 light_normal, float4 light_position, float lambertian_probability, bool is_opaque);
